import {
    Target, Waypoints, ArrowDown10, GitFork, Infinity as InfinityIcon, Settings,
    Hammer, RotateCcw, History, Swords, SplitSquareHorizontal,
    Link, Combine, Brain, Component, PlaySquare, FlaskConical,
    AlertTriangle, LightbulbOff, XOctagon, Zap, Maximize,
    Shuffle, TextQuote, BadgeCheck, PieChart, BookMarked,
    CheckSquare, MoveRight, Telescope, Box, Flame, GraduationCap, Baby, GitMerge, Code,
    ClipboardList, Plug, Database, Blocks, Package, Puzzle,
    Calculator, Palette, MessageSquare, Footprints, Map, Scale,
    Search, ShieldCheck, ListChecks, Bug, Shapes, Truck, FileText,
    GitPullRequest, GitBranch, Radio, PackageSearch,
    Accessibility, Rocket, ShieldAlert, KeyRound, Server
} from 'lucide-react';

export const MODULE_ICONS = {
    // Learning domain
    kalibrasyon: Target,
    onkosul: Waypoints,
    sirasi: ArrowDown10,
    ontoloji: GitFork,
    nedensellik: InfinityIcon,
    mekanizma: Settings,
    insa: Hammer,
    tersine: RotateCcw,
    evrim: History,
    rakip: Swords,
    kontrast: SplitSquareHorizontal,
    esleme: Link,
    disiplinler: Combine,
    mental: Brain,
    diagram: Component,
    simulasyon: PlaySquare,
    deney: FlaskConical,
    yanilgilar: AlertTriangle,
    varsayimlar: LightbulbOff,
    basarisizlik: XOctagon,
    kirilma: Zap,
    olcek: Maximize,
    celiski: Shuffle,
    ornekler: TextQuote,
    uzman: BadgeCheck,
    pareto: PieChart,
    kaynak: BookMarked,
    quiz: CheckSquare,
    transfer: MoveRight,
    gelecek: Telescope,
    meta: GraduationCap,
    senaryo: Flame,
    eli5: Baby,
    karar: GitMerge,
    kodlama: Code,
    // Code domain
    'req-clarify': ClipboardList,
    'api-design': Plug,
    'data-model': Database,
    architecture: Blocks,
    'tech-select': Package,
    implement: Hammer,
    scaffold: Puzzle,
    algorithm: Calculator,
    idioms: Palette,
    explain: MessageSquare,
    trace: Footprints,
    'codebase-map': Map,
    'compare-approaches': Scale,
    review: Search,
    security: ShieldCheck,
    performance: Zap,
    tests: ListChecks,
    'edge-cases': Target,
    debug: Bug,
    refactor: RotateCcw,
    patterns: Shapes,
    migration: Truck,
    docs: FileText,
    'commit-pr': GitPullRequest,
    concurrency: GitBranch,
    observability: Radio,
    'supply-chain': PackageSearch,
    a11y: Accessibility,
    cicd: Rocket,
    'threat-model': ShieldAlert,
    'auth-design': KeyRound,
    'infra-security': Server
};

export function getModuleIcon(moduleId) {
    return MODULE_ICONS[moduleId] || Box;
}
